#!/usr/bin/env python3
"""
Equipment Asset Management - Simple Report Generator
生成简化版 Markdown 报告
"""

import json
import argparse
from pathlib import Path
from datetime import datetime
from calculate_cost import calculate


def generate_markdown_report(data: dict) -> str:
    """生成 Markdown 报表"""
    
    meta = data.get("meta", {})
    equipment_list = data.get("equipment", [])
    
    lines = [
        "# 📱 Equipment Asset Report",
        "",
        f"> Generated: {meta.get('calculated_at', datetime.now().strftime('%Y-%m-%d %H:%M'))}",
        f"> Base Currency: {meta.get('base_currency', 'CNY')}",
        "",
        "---",
        "",
        "## 📊 Summary",
        "",
    ]
    
    # 统计数据
    total_price = sum(item.get("price", 0) for item in equipment_list)
    total_residual = sum(item.get("residual_value", 0) for item in equipment_list)
    
    lines.extend([
        f"- **Total Equipment**: {len(equipment_list)} items",
        f"- **Total Investment**: ¥{total_price:,.2f}",
        f"- **Residual Value**: ¥{total_residual:,.2f}",
        f"- **Depreciation**: ¥{total_price - total_residual:,.2f} ({((total_price - total_residual)/total_price*100):.1f}%)",
        "",
        "---",
        "",
        "## 📋 Equipment List",
        "",
    ])
    
    # 分类
    categories = {}
    for item in equipment_list:
        cat = item.get("category", "other")
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(item)
    
    cat_names = {
        "computer": "💻 Computer",
        "phone": "📱 Phone",
        "tablet": "📱 Tablet",
        "wearable": "⌚ Wearable",
        "smart-home": "🏠 Smart Home",
        "other": "📦 Other"
    }
    
    for cat, items in sorted(categories.items()):
        lines.extend([
            f"### {cat_names.get(cat, cat)} ({len(items)} items)",
            "",
            "| Name | Purchase | Price | Days | Daily Cost | Status | Residual |",
            "|:---|:---|---:|---:|---:|:---|---:|",
        ])
        
        for item in items:
            lines.append(
                f"| {item.get('name', 'N/A')[:20]} | "
                f"{item.get('purchase_date', '-')} | "
                f"¥{item.get('price', 0):,.0f} | "
                f"{item.get('days_used', 0)} | "
                f"¥{item.get('daily_cost', 0):.1f} | "
                f"{item.get('status_emoji', '⚪')} {item.get('status', '')} | "
                f"¥{item.get('residual_value', 0):,.0f} |"
            )
        
        cat_price = sum(i.get("price", 0) for i in items)
        cat_residual = sum(i.get("residual_value", 0) for i in items)
        lines.extend([
            "",
            f"**Subtotal**: ¥{cat_price:,.0f} → ¥{cat_residual:,.0f}",
            "",
        ])
    
    lines.extend([
        "---",
        "",
        "## 💡 Recommendations",
        "",
        "### 🟢 Keep Using",
        "",
    ])
    
    for item in equipment_list:
        if item.get("daily_cost", 0) < 10:
            lines.append(f"- **{item.get('name')}**: Daily cost ¥{item.get('daily_cost', 0):.1f} - very cost-effective")
    
    lines.extend([
        "",
        "### 🔴 Consider Replacement",
        "",
    ])
    
    for item in equipment_list:
        if item.get("years_used", 0) > 4:
            lines.append(f"- **{item.get('name')}**: Used {item.get('years_used', 0):.1f} years - consider upgrading")
    
    lines.extend([
        "",
        "---",
        "",
        "_Generated by Equipment Asset Management_",
        "",
    ])
    
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="生成设备报表")
    parser.add_argument("--input", "-i", required=True, help="输入 JSON 文件")
    parser.add_argument("--output", "-o", help="输出文件路径")
    args = parser.parse_args()
    
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"❌ 文件不存在: {input_path}")
        return 1
    
    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    report = generate_markdown_report(data)
    
    if args.output:
        output_path = Path(args.output)
        output_path.write_text(report, encoding="utf-8")
        print(f"✅ 报表已保存: {output_path}")
    else:
        print(report)
    
    return 0


if __name__ == "__main__":
    exit(main())
